services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  mongo:
    image: mongo:7.0.3
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  gateway-service:
    image: gateway-service:latest
    build:
      dockerfile: ./gateway-service/Dockerfile
    restart: on-failure
    volumes:
      - ./gateway-service.env:/app/application.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: frontend:latest
    build:
      dockerfile: ./frontend/Dockerfile
    restart: on-failure
    volumes:
      - ./frontend.env:/app/application.env
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"