services:
  gateway:
    build:
      context: ./gateway-service
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongo
    volumes:
      - ./prod.env:/app/application.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: frontend:latest
    build:
      context: ./frontend
    restart: on-failure
    depends_on:
      - gateway
    ports:
      - "80:80"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  mongo:
    image: mongo:7.0.3
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - ./tools/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
