GET http://localhost:10000/api/v1/passwords/
Accept: application/json

###

POST http://localhost:10000/api/v1/passwords/
Accept: application/json
Content-Type: application/json

{
  "password": "demhns123123adsads213213123ad132"
}

###

GET http://localhost:10000/api/v1/passwords/6575b9bfa60e2383e67cb4da
Accept: application/json

###