GET http://localhost:10000/api/v1/passwords/
Accept: application/json

###

POST http://localhost:10000/api/v1/passwords/
Accept: application/json
Content-Type: application/json

{
  "password": "as3as321"
}

###

GET http://localhost:10000/api/v1/passwords/as3as321
Accept: application/json

###

PATCH http://localhost:10000/api/v1/passwords/as3as32123213
Content-Type: application/json
Accept: application/json

{
  "strength": 2
}

###